### PR TITLE
requirements: Update all requirements

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Python 3.7 comment removed by tool - this was generated on Python 3.6, same as tests run on

**Comment by michaelwood** [comment]
Could this be done for python3.8 . The datastore is running 3.8 and is the primary user of the datagetter. May require update to CI. Thanks

**Comment by ghost** [comment]
[Datagetter - update all requirements](https://trello.com/c/fB6EDPGr/222-datagetter-update-all-requirements)

**Comment by ghost** [comment]
I can set Python 3.8 as min requirements for this in setup.py, update GitHub actions and rebuild deps - if we are sure no-one is using it below that?

**Comment by ghost** [comment]
Chatted to @michaelwood - we'll do deps in Python 3.8, test in 3.6 -> 3.10, and put a note in the readme to say to anyone doing future dep work should use 3.8 & also 3.8 is the supported version

**Review by michaelwood — CHANGES_REQUESTED** [review]
Do the tests run correctly before the requirements file was updated?

I'd like this to be in 3 commits really. To help make all commits atomic, one way I test that assertion is thinking like "If I wanted to revert the changes in the README I couldn't do that without also reverting requirements and test changes."

**Comment by ghost** [comment]
I would argue 2 commits - the changes to the README document changes to the requirements file, so they really have to go together. Reverting the readme so it says "3.6" without also reverting the reqs doesn't make sense to me.

I'll do one commit with the GitHub changes - which will also answer your question - and a 2nd with docs & req.

**Comment by ghost** [comment]
> Do the tests run correctly before the requirements file was updated?

Yes https://github.com/ThreeSixtyGiving/datagetter/actions/runs/1477517053

**Review by michaelwood — APPROVED** [review]

**Pull request merged**
